"""Notifications generated by invites, RSVPs, cancellations, and connections."""

from tests.conftest import event_payload


async def user_id(client):
    return (await client.get("/api/users/me")).json()["id"]


async def connect(requester, addressee):
    """Create an accepted connection between two user-clients."""
    conn = (
        await requester.post(
            "/api/connections", json={"addressee_id": await user_id(addressee)}
        )
    ).json()
    await addressee.patch(f"/api/connections/{conn['id']}", json={"status": "accepted"})


async def notifs(client):
    return (await client.get("/api/notifications")).json()


async def unread(client):
    return (await client.get("/api/notifications/unread-count")).json()["count"]


async def test_invite_notifies_invitee(make_user):
    host = await make_user("host@example.com", "Host")
    friend = await make_user("friend@example.com", "Friend")
    await connect(host, friend)
    event = (await host.post("/api/events", json=event_payload(title="Picnic"))).json()

    await host.post(
        f"/api/events/{event['id']}/invites", json={"user_id": await user_id(friend)}
    )

    invite = next(n for n in await notifs(friend) if n["type"] == "event_invite")
    assert "invited you to Picnic" in invite["message"]
    assert invite["link"] == f"/events/{event['id']}"


async def test_rsvp_notifies_host(make_user):
    host = await make_user("host@example.com", "Host")
    guest = await make_user("guest@example.com", "Guest")
    event = (await host.post("/api/events", json=event_payload(title="Board games"))).json()

    await guest.put(f"/api/events/{event['id']}/rsvp", json={"status": "going"})

    rsvp = next(n for n in await notifs(host) if n["type"] == "event_rsvp")
    assert "is going to Board games" in rsvp["message"]


async def test_cancel_notifies_attendees(make_user):
    host = await make_user("host@example.com", "Host")
    guest = await make_user("guest@example.com", "Guest")
    event = (await host.post("/api/events", json=event_payload(title="Cleanup"))).json()
    await guest.put(f"/api/events/{event['id']}/rsvp", json={"status": "going"})

    await host.patch(f"/api/events/{event['id']}", json={"status": "cancelled"})

    cancelled = next(n for n in await notifs(guest) if n["type"] == "event_cancelled")
    assert "Cleanup was cancelled" in cancelled["message"]


async def test_connection_request_and_accept_notify(make_user):
    ann = await make_user("ann@example.com", "Ann")
    bo = await make_user("bo@example.com", "Bo")
    conn = (
        await ann.post("/api/connections", json={"addressee_id": await user_id(bo)})
    ).json()
    # Bo (the addressee) hears about the request.
    assert any(n["type"] == "connection_request" for n in await notifs(bo))

    await bo.patch(f"/api/connections/{conn['id']}", json={"status": "accepted"})
    # Ann (the requester) hears it was accepted.
    assert any(n["type"] == "connection_accepted" for n in await notifs(ann))


async def test_mark_read_clears_unread_count(make_user):
    host = await make_user("host@example.com", "Host")
    guest = await make_user("guest@example.com", "Guest")
    event = (await host.post("/api/events", json=event_payload())).json()
    await guest.put(f"/api/events/{event['id']}/rsvp", json={"status": "going"})

    assert await unread(host) >= 1
    r = await host.post("/api/notifications/read")
    assert r.status_code == 204
    assert await unread(host) == 0


async def test_no_self_notification(make_user):
    # The host posting in their own event shouldn't notify themselves.
    host = await make_user("host@example.com", "Host")
    event = (await host.post("/api/events", json=event_payload())).json()
    await host.post(f"/api/events/{event['id']}/messages", json={"body": "hello"})
    assert await unread(host) == 0
