"""baseline

Revision ID: f5577b81b7f0
Revises: 
Create Date: 2026-07-08 13:00:42.488253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5577b81b7f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostGIS backs the geography columns created in later migrations. Enable it
    # up front so a fresh database (e.g. a managed Postgres on first deploy)
    # migrates cleanly without a manual step. Idempotent — a no-op where it's
    # already installed.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
